robot: "bench"
address: "127.0.0.1"
cameras:
  bench:
    name: "bench_ros_raw"
    input:
      type: ros2
      topic: "/bench/image_raw"
      format: raw
    outputs:
      - type: rtp
        codec: h264
        encoder: ${BENCH_RCS_ENC}
        framerate: "30/1"
        host: "127.0.0.1"
        port: 7100
        bitrate: 1000
        width: ${BENCH_WIDTH}
        height: ${BENCH_HEIGHT}
